nao_platform_home:
    path:     /
    defaults: { _controller: NAOPlatformBundle:Platform:index }
    methods:  [GET]

nao_platform_rechercher:
    path:     /rechercher
    defaults: { _controller: NAOPlatformBundle:Platform:rechercher }
    methods:  [GET, POST]

nao_platform_observer:
    path:     /observer
    defaults: { _controller: NAOPlatformBundle:Platform:observer}
    methods:  [GET, POST]

nao_platform_demande:
    path:     /demande
    defaults: { _controller: NAOPlatformBundle:Platform:demande}
    methods:  [GET, HEAD, POST]

nao_platform_autosearch:
    path:     /autosearch
    defaults: { _controller: NAOPlatformBundle:Autocomplete:autosearch}
    methods: [GET]

nao_platform_autoget:
    path:    /autoget/{id}
    defaults: { _controller: NAOPlatformBundle:Autocomplete:autoget, id: null}
    methods: [GET]

fos_user_security_login:
    path:     /connexion
    defaults: { _controller: NAOPlatformBundle:Security:login}
    methods:  [GET, POST]

fos_user_security_check:
    path:     /connexion_check
    defaults: { _controller: FOSUserBundle:Security:check}
    methods:  [POST]

fos_user_security_logout:
    path:     /deconnexion
    defaults: { _controller: FOSUserBundle:Security:logout}
    methods:  [GET, POST]

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
