nao_platform_home:
    path:     /
    defaults: { _controller: NAOPlatformBundle:Platform:index }
    methods:  [GET]

nao_platform_rechercher:
    path:     /rechercher
    defaults: { _controller: NAOPlatformBundle:Platform:rechercher }
    methods:  [GET, POST]

nao_platform_observer:
    path:     /observer
    defaults: { _controller: NAOPlatformBundle:Platform:observer}
    methods:  [GET, POST]

nao_platform_demande:
    path:     /demande
    defaults: { _controller: NAOPlatformBundle:Platform:demande}
    methods:  [GET, HEAD, POST]

