services:
#    nao_platform.example:
#        class: NAO\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    nao_platform.jsonencode:
        class: NAO\PlatformBundle\Services\JsonEncode\NAOJsonEncode
