services:
#    nao_platform.example:
#        class: NAO\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    nao_platform.jsonencode:
        class: NAO\PlatformBundle\Services\JsonEncode\NAOJsonEncode

    nao_platform.fileuploader:
        class: NAO\PlatformBundle\Services\FileUploader\NAOFileUploader
        arguments:
            photodirectory: '%photos_directory%'
            pdfdirectory: '%pdf_directory%'

    nao_platform.sendmail:
        class: NAO\PlatformBundle\Services\SendMail\NAOSendMail
        arguments: ['@mailer']
