# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        NAO\PlatformBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER :         ROLE_USER                                 #particulier
        ROLE_ADMIN :        [ROLE_USER, ROLE_ADMIN]                   #naturaliste
        ROLE_SUPER_ADMIN :  [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN] #admin

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:      ^/
            anonymous:    true
            form_login:
                provider:             fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:           fos_user_security_login
                use_forward:          false
                check_path:           fos_user_security_check
                failure_path:         null
                default_target_path:  fos_user_profile_show
                remember_me:          true
            logout:
                 path:       fos_user_security_logout
                 target:     /
            remember_me:
                 secret:    %secret% # %secret% est un paramètre de parameter
                 lifetime:  2419200 # 1 month in seconds
                 path:      /
                 domain:   ~

    access_control:
        - { path: ^/connexion, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rechercher, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/observer, role: IS_AUTHENTICATED_ANONYMOUSLY } #attention à mettre dans le controlleur qu'en post il faut avoir le role SUPER_ADMIN
        - { path: ^/profile/observationsvalidees, role: ROLE_ADMIN }
        - { path: ^/profile/comptesnaturalistes, role: ROLE_SUPER_ADMIN }
        - { path: ^/profile/mesobservations, role: ROLE_USER}
        - { path: ^/profile/observationsenattente, role: ROLE_ADMIN}
        - { path: ^/profile/observationsrefusees, role: ROLE_ADMIN}
        - { path: ^/profile/admin/^, role: ROLE_SUPER_ADMIN }
        - { path: ^/profile/admin/listenaturaslistes, role: ROLE_SUPER_ADMIN }