<?php

namespace NAO\PlatformBundle\Repository;

/**
 * EspeceNomLatinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspeceNomLatinRepository extends \Doctrine\ORM\EntityRepository
{
}
