<?php

namespace NAO\PlatformBundle\Repository;

/**
 * NaturalisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NaturalisteRepository extends \Doctrine\ORM\EntityRepository
{
}
