<?php

namespace NAO\PlatformBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    function getListObsByUser($id)    {
        $qb = $this->createQueryBuilder('obs')
            ->leftJoin('obs.user', 'user')
            ->where('user.id = :id_user')
            ->setParameter('id_user', $id);
        return $qb->getQuery()->getResult();
    }

    function getListObsNonvalideEnAttente() {
        $qb = $this->createQueryBuilder('obs')
            ->leftJoin('obs.user', 'user')
            ->where('obs.valide = :valide')
            ->andWhere('user.typeCompte = :typeCompte')
            ->andWhere('obs.enAttente = :enAttente')
            ->setParameters(array('valide' => false, 'typeCompte' => 0, 'enAttente' => true));
        return $qb->getQuery()->getResult();
    }

    //pour récupérer les observations traitées par un naturaliste
    function getListObsTraiteeParNaturaliste($id) {
        $qb = $this->createQueryBuilder('obs')
            ->leftJoin('obs.validateur', 'user')
            ->where('user.id = :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }

    //pour récupérer les observations refusées par un naturaliste
    function getListObsRefuseesParNaturaliste($id) {
        $qb = $this->createQueryBuilder('obs')
            ->leftJoin('obs.validateur', 'user')
            ->where('user.id = :id')
            ->andWhere('obs.valide = :valid')
            ->andWhere('obs.enAttente = :enAttente')
            ->setParameters(array(
                'id'=> $id,
                'valid'=>false,
                'enAttente'=>false
            ));
        return $qb->getQuery()->getResult();
    }

    function getAllObserv() { // Pour l'export de toutes les observations
        return $this->createQueryBuilder('obs')->getQuery()->getResult();
    }

    function getDerObsValides($jours) { // Observation des X derniers jours / à mettre sur la page d'accueil ?
        $qb = $this->createQueryBuilder('obs')
            ->where('obs.dateObs > :todayMoinsJours')
            ->andWhere('obs.valide = :valide')
            ->setParameters(array(
                'todayMoinsJours' => (new \Datetime())->sub(new \DateInterval('P'.$jours.'D')),
                'valide' => true
                ));
        return $qb->getQuery()->getResult();
    }

    //récupère les observations valides pour une liste d'id d'espèces
    function getListObsByEspeceValides($listEspece) {
        $listEspeceId = [];
        foreach ($listEspece as $espece){
            array_push($listEspeceId, $espece->getId());
        }
        $qb = $this->_em->createQuery("SELECT obs FROM NAOPlatformBundle:Observation obs JOIN obs.especeNomVern esp WHERE esp.id IN(:listeEspeceId) AND obs.valide=:valide")
            ->setParameters(array(
                'valide' => true,
                'listeEspeceId' => $listEspece
            ));
        return $qb->getResult();
    }
}
