<?php

namespace NAO\PlatformBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    function getListObsByUser($id)
    {
        $qb = $this->createQueryBuilder('obs')
            ->leftJoin('obs.user', 'user')
            ->where('user.id = :id_user')
            ->setParameter('id_user', $id);
        return $qb->getQuery()->getResult();
    }

    function getListObsNonvalide() {
        $qb = $this->createQueryBuilder('obs')
            ->leftJoin('obs.user', 'user')
            ->where('obs.valide = :valide')
            ->andWhere('user.typeCompte = :typeCompte')
            ->setParameters(array('valide' => false, 'typeCompte' => 0));
        return $qb->getQuery()->getResult();
    }

    function getAllObserv() { // Pour l'export de toutes les observations
        return $this->createQueryBuilder('obs')->getQuery()->getResult();
    }

    function getDerObs($jours) {
        $qb = $this->createQueryBuilder('obs')
            ->where('obs.dateObs > :todayMoinsJours')
            ->setParameter('todayMoinsJours', (new \Datetime())->sub(new \DateInterval('P'.$jours.'D')) );
        return $qb->getQuery()->getResult();
    }
}
